spring:
  application:
    name: eureka-server
  security:
    user:
      name: username
      password: pass
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false